### ISSUE TITLE
New features (advantage/disadvantage/average damage) need some tweaking

### ISSUE THREAD

**Issue by keanfreeman** [keanfreeman/swarm-roller-dnd-5e#4]
Right now, a user who tries to make the swarm attack must re-enter whether they would like the attack to have advantage/disadvantage and average damage displayed every time. I think for the sake of speed, these options should be available somewhere else, perhaps another option in the main menu.

**Comment by nicwineburger** [comment]
Agreed. But then we would then have 7 menu options: roll attack, roll attack w/ adv, roll attack w/ dis, average attack, average attack w/adv, average attack w/ dis, takes damage. Seems inelegant. 

Maybe we make it command based instead of menu based? As in, the user would be prompted for input like: <roll/average/damage> <adv/dis>. This also might make future features, such as saving throws, less cumbersome to introduce

**Comment by keanfreeman** [comment]
Could you give me an example of how an attack command would go in that case?

**Comment by nicwineburger** [comment]
Example: user wants to roll the attack with advantage 
input = roll adv
Example: user wants to use the average damage value with disadvantage
input = average dis

Recent commit implements this.
